# Generated by Django 4.0.4 on 2022-11-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
