# Generated by Django 4.0.4 on 2022-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
