# Generated by Django 4.0.4 on 2022-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0003_textimgsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimgsum',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='summariser/files/imgs'),
        ),
    ]
